* 参考教程

** 机器学习实战 handson-ml
https://github.com/ageron/handson-ml

https://github.com/apachecn/hands-on-ml-zh

特点: 较早展示代码和相关工具，较早进入实战。
不应该纠结理论细节。

** 吴恩达机器学习
特点: 数学要求低，基本高中毕业即可
Octave 类似matlab

** d2l.ai
特点: 一开始就提示要哪些数学基础: 微积分、线性代数、概率论

亚马逊人工智能团队主导
李沐

* 机器学习概览

** 什么是机器学习?

通过编程让计算机从数据中学习的计算机科学和技术

关键词: 编程、数据、学习

** 机器学习的分类

*** 是否需人类监督
有监督学习、无监督学习、半监督学习、强化学习

监督学习: 标签(答案)

分类和回归的区别: 可取值值域的离散和连续
垃圾邮件、预测房价二手车价

**** 无监督学习
降维:将多个相关特征合并为一个，故名降维。
目的是在不丢失太多信息的前提下简化数据。
这个过程也叫特征提取。

例子: 对博客、公众号的访客进行分组

**** 半监督学习
少量标记数据。
如Google相册。

**** 强化学习
观察环境，做出选择，根据回报或惩罚，调整策略，不断学习得到最好策略。
AlphaGo。

与监督学习和无监督学习最大的不同，就在于强化学习里，并没有给定的一组数据供智能体学习。环境是不断变化的，强化学习智能体要在变化的环境里，做出一系列动作的决策，而不是某一个动作的决策。一系列决策结合起来就是策略，强化学习就是通过不断与环境互动 (不断试错) ，更新策略的过程。
//未给定一组数据
//何为策略: 一系列决策的结合。
*** 是否动态增量地学习
在线学习、离线(批量)学习

超出单台计算机主存储器的学习，叫核外学习


**** 批量学习 -- 翻译为"全量学习"可能更合适
必须使用所有可用数据进行训练。 通常离线完成。
很可能需要每天甚至每周训练一次新系统，无法应对快速变化的数据(如预测股票价格)

**** 在线学习 -- 增量学习
整个过程通常离线完成，故称其为增量学习更好。
核外学习: 超出一台计算机的主存储器的数据集。

可以小批量地增加训练数据。

学习率: 增量学习适应不断变化的数据的速度。
学习率高: 迅速适应新数据，但有也很快忘记旧数据(比如导致垃圾邮件过滤器只针对最近的邮件有效)
学习率低: 学习过程缓慢

*** 是否建立模型
**** 基于实例的学习(简单模仿)
相似度度量: 判定垃圾邮件

**** 基于模型的学习
主流

选择模型

评估模型: 成本函数

** 机器学习能做什么

垃圾邮件过滤
推荐系统(今日头条、知乎)
AlphaGo

关键词: 优化、解决、洞见


领域知识+机器学习>>单一的机器学习

** 机器学习的主要挑战

训练数据数量不足

训练数据不具代表性

数据质量差
？高层模式是什么？ 

无关特征: 特征提取

算法过度拟合

算法拟合不足

** 测试与验证
* QQ电话
点开视频，关视频，点屏幕分享

录屏只录取了听众的声音，无主讲的声音。
需要在听众侧录屏才有主讲的声音。
